// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw0y5bv1ijA_efONz1jo9TfZT3KPoogJ8',
    appId: '1:94712880912:web:d3b4906759aa3f6dbf4f95',
    messagingSenderId: '94712880912',
    projectId: 'fintrack-6b6d4',
    authDomain: 'fintrack-6b6d4.firebaseapp.com',
    storageBucket: 'fintrack-6b6d4.firebasestorage.app',
    measurementId: 'G-BS8JND5STR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcfdKFmanSmq5fNiVm0Tz3V0Ri-ANVvA',
    appId: '1:94712880912:android:8e6d87421b2aadf7bf4f95',
    messagingSenderId: '94712880912',
    projectId: 'fintrack-6b6d4',
    storageBucket: 'fintrack-6b6d4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw0y5bv1ijA_efONz1jo9TfZT3KPoogJ8',
    appId: '1:94712880912:web:a0b5f4df5420d648bf4f95',
    messagingSenderId: '94712880912',
    projectId: 'fintrack-6b6d4',
    authDomain: 'fintrack-6b6d4.firebaseapp.com',
    storageBucket: 'fintrack-6b6d4.firebasestorage.app',
    measurementId: 'G-QS1VJL5NK2',
  );
}
